version: '3.7'

services:
  api:
    image: skyanalytics-api
    container_name: skyanalytics-api
    ports:
      - 3000:3000
    networks:
      - skyanalytics-network
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
  
  db:
    image: mysql:9.0.0
    container_name: skyanalytics-db
    ports:
      - 4462:3306
    volumes:
      - ./.db:/var/lib/mysql
    networks:
      - skyanalytics-network
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

networks:
  skyanalytics-network: