version: '3.7'

services:
  backend:
    profiles: 
      - prod
    build: 
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: skyanalytics-backend
    networks:
      - skyanalytics-network
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}

  frontend:
    profiles: 
      - prod
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: skyanalytics-frontend
    networks:
      - skyanalytics-network
  
  db:
    image: postgres:16-alpine
    container_name: skyanalytics-db
    ports:
      - 4258:5432
    volumes:
      - ./.db:/var/lib/postgresql/data
    networks:
      - skyanalytics-network
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

networks:
  skyanalytics-network:
    name: skyanalytics-network