version: '3.7'

services:
  frontend:
    profiles: 
      - prod
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: skyanalytics-frontend
    ports:
      - ${PORT_FRONTEND}:8080
      - ${PORT_FRONTEND_NITRO}:3000
    networks:
      - skyanalytics-network
    environment:
      - URL_BACKEND=${URL_BACKEND}

  backend:
    profiles: 
      - prod
    build: 
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: skyanalytics-backend
    restart: on-failure:5
    ports:
      - ${PORT_BACKEND}:3000
    volumes:
      - ./uploads:/app/dist/uploads
    networks:
      - skyanalytics-network
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
  
  db:
    image: postgres:16-alpine
    container_name: skyanalytics-db
    ports:
      - 4258:5432
    volumes:
      - ./.db:/var/lib/postgresql/data
    networks:
      - skyanalytics-network
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

networks:
  skyanalytics-network:
    name: skyanalytics-network