version: '3.7'

services:
  api:
    profiles: 
      - prod
    build: 
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: skyanalytics-api
    networks:
      - skyanalytics-network
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}

  web:
    profiles: 
      - prod
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: skyanalytics-web
    networks:
      - skyanalytics-network
  
  db:
    image: postgres:16-alpine
    container_name: skyanalytics-db
    ports:
      - 4258:5432
    volumes:
      - ./.db:/var/lib/postgresql/data
    networks:
      - skyanalytics-network
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    image: nginx:alpine
    container_name: skyanalytics-nginx
    ports:
      - 81:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - skyanalytics-network
    depends_on:
      - db

networks:
  skyanalytics-network: