name: 'skyanalytics'
description: 'SkyAnalytics Flutter is an adapter for [SkyAnalytics]. It provides a way to use SkyAnalytics in your Flutter application.'
version: 0.0.3
homepage: https://github.com/carum98/skyanalytics/tree/main/packages/adapters/flutter
issue_tracker: https://github.com/carum98/skyanalytics/issues
documentation: https://github.com/carum98/skyanalytics/tree/main/packages/adapters/flutter#readme

platforms:
  android:
  ios:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter: