services:
  api:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      - .:/workspace:cached
      - /workspace/node_modules
