services:
  dev:
    profiles: 
      - dev
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - .:/workspace:cached
      - /workspace/node_modules
    networks:
      - skyanalytics-network
    depends_on:
      - db
    env_file:
      - ./packages/backend/.env
      - ./packages/frontend/.env

  nginx:
    profiles: 
      - dev
    image: nginx:alpine
    container_name: skyanalytics-nginx
    ports:
      - 81:80
    volumes:
      - .devcontainer/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - skyanalytics-network
    depends_on:
      - db