services:
  dev:
    profiles: 
      - dev
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - .:/workspace:cached
      - /workspace/node_modules
    networks:
      - skyanalytics-network
    depends_on:
      - db
    env_file:
      - .env
